name: GitHub Actions Demo
on:   
  push:
    branches: 
      - manager
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
      - name: Check out repository code
        uses: actions/checkout@v2
      
      - name: Set up Node
        uses: actions/setup-node@v1
        with:
            node-version: 2
      - name: Run Super-Linter
        uses: github/super-linter@v3
        env:
          DEFAULT_BRANCH: manager
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
